line: test1
tt_sec: 2
count_per_cycle: 1
threshold: 80
day_start: 08:00
night_start: 06:08
reset_day_time: 07:50
reset_night_time: 06:07
day_breaks:
- enabled: true
  start: 06:10
  end: 06:11
night_breaks:
- enabled: true
  start: 06:26
  end: 06:27
enable: true
updated_at: '2024-08-27 06:25:46'
