line: test3
tt_sec: 5
count_per_cycle: 1
threshold: 80
day_start: 08:00
night_start: '20:00'
reset_day_time: 07:59
reset_night_time: '19:59'
day_breaks:
- enabled: true
  start: 08:02
  end: 08:03
night_breaks:
- enabled: true
  start: 08:28
  end: 08:29
enable: true
updated_at: '2024-08-31 05:59:33'
